//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWSEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public Dictionary()
        {
            this.DictionaryGlosses = new HashSet<DictionaryGloss>();
        }
    
        public long IDDictionary { get; set; }
        public Nullable<long> IDSignLanguage { get; set; }
        public Nullable<bool> isPrivate { get; set; }
        public Nullable<int> bkColor { get; set; }
        public byte[] SWriting { get; set; }
        public byte[] Photo { get; set; }
        public byte[] Sign { get; set; }
        public string SWritingSource { get; set; }
        public string PhotoSource { get; set; }
        public string SignSource { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string IDSignPuddle { get; set; }
        public string SignPuddleUser { get; set; }
        public string PuddlePrev { get; set; }
        public string PuddleNext { get; set; }
        public string PuddlePNG { get; set; }
        public string PuddleSVG { get; set; }
        public string PuddleVideoLink { get; set; }
    
        public virtual ICollection<DictionaryGloss> DictionaryGlosses { get; set; }
    }
}
