//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWSEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frame
    {
        public long IDFrame { get; set; }
        public Nullable<long> IDDictionary { get; set; }
        public Nullable<int> FrameIndex { get; set; }
        public Nullable<int> Left { get; set; }
        public Nullable<int> Top { get; set; }
        public Nullable<int> MinWidth { get; set; }
        public Nullable<int> MinHeight { get; set; }
    }
}
