//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWSEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuddleText
    {
        public long IDPuddleText { get; set; }
        public Nullable<long> IDDictionary { get; set; }
        public string EntryText { get; set; }
    }
}
