//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWSEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SigninSignListSubTitle
    {
        public long IDSigninSignListSubTitle { get; set; }
        public Nullable<long> IDSignListSubTitle { get; set; }
        public Nullable<long> IDDictionary { get; set; }
        public Nullable<bool> isNewSign { get; set; }
        public Nullable<bool> isImportant { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<System.DateTime> LastChange { get; set; }
    }
}
