//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWSEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignSequence
    {
        public long IDSignSequence { get; set; }
        public Nullable<long> IDFrame { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<int> rank { get; set; }
    }
}
