//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWSEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignSymbol
    {
        public long IDSignSymbols { get; set; }
        public Nullable<long> IDFrame { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
        public Nullable<int> z { get; set; }
        public Nullable<int> hand { get; set; }
        public Nullable<int> handcolor { get; set; }
        public Nullable<int> palmcolor { get; set; }
        public Nullable<int> size { get; set; }
    }
}
