//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWSEF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SWSEntities : DbContext
    {
        public SWSEntities()
            : base("name=SWSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dictionary> Dictionaries { get; set; }
        public virtual DbSet<DictionaryGloss> DictionaryGlosses { get; set; }
        public virtual DbSet<Frame> Frames { get; set; }
        public virtual DbSet<PuddleText> PuddleTexts { get; set; }
        public virtual DbSet<SigninSignListSubTitle> SigninSignListSubTitles { get; set; }
        public virtual DbSet<SignList> SignLists { get; set; }
        public virtual DbSet<SignListSubTitle> SignListSubTitles { get; set; }
        public virtual DbSet<SignSequence> SignSequences { get; set; }
        public virtual DbSet<SignSymbol> SignSymbols { get; set; }
        public virtual DbSet<Version> Versions { get; set; }
    }
}
