//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.

using System.Data.Linq.Mapping; 
using SQLite;
using System;

namespace Dictionary
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Dictionary>();
                db.CreateTable<DictionaryGloss>();
                db.CreateTable<Frame>();
                db.CreateTable<PuddleText>();
                db.CreateTable<SigninSignListSubTitles>();
                db.CreateTable<SignList>();
                db.CreateTable<SignListSubTitles>();
                db.CreateTable<SignSequence>();
                db.CreateTable<SignSymbols>();
                db.CreateTable<Version>();
            }
        }
    }
    
    public partial class Dictionary
    {
        [PrimaryKey]
        public Int64 IDDictionary { get; set; }
        public Int64 IDSignLanguage { get; set; }
        public Boolean isPrivate { get; set; }
        public Int32 bkColor { get; set; }
        public Byte[] SWriting { get; set; }
        public Byte[] Photo { get; set; }
        public Byte[] Sign { get; set; }
        [MaxLength(2147483647)]
        public String SWritingSource { get; set; }
        [MaxLength(2147483647)]
        public String PhotoSource { get; set; }
        [MaxLength(2147483647)]
        public String SignSource { get; set; }
        public Guid GUID { get; set; }
        public DateTime Created { get; set; }
        public DateTime LastModified { get; set; }
        [MaxLength(2147483647)]
        public String IDSignPuddle { get; set; }
        [MaxLength(2147483647)]
        public String SignPuddleUser { get; set; }
        [MaxLength(2147483647)]
        public String PuddlePrev { get; set; }
        [MaxLength(2147483647)]
        public String PuddleNext { get; set; }
        [MaxLength(2147483647)]
        public String PuddlePNG { get; set; }
        [MaxLength(2147483647)]
        public String PuddleSVG { get; set; }
        [MaxLength(2147483647)]
        public String PuddleVideoLink { get; set; }
    }

    [System.Data.Linq.Mapping.Table]
    public partial class DictionaryGloss
    {
        [PrimaryKey]
        [System.Data.Linq.Mapping.Column(Name = "IDDictionaryGloss")]
        public Int64 IDDictionaryGloss { get; set; }
        [System.Data.Linq.Mapping.Column(Name = "IDDictionary")]
        public Int64 IDDictionary { get; set; }
        [System.Data.Linq.Mapping.Column(Name = "IDCulture")]
        public Int64 IDCulture { get; set; }
        [System.Data.Linq.Mapping.Column(Name = "gloss")]
        [MaxLength(2147483647)]
        public String gloss { get; set; }
        [System.Data.Linq.Mapping.Column(Name = "glosses")]
        [MaxLength(2147483647)]
        public String glosses { get; set; }
    }
    public partial class Frame
    {
        [PrimaryKey]
        public Int64 IDFrame { get; set; }
        public Int64 IDDictionary { get; set; }
        public Int32 FrameIndex { get; set; }
        public Int32 Left { get; set; }
        public Int32 Top { get; set; }
        public Int32 MinWidth { get; set; }
        public Int32 MinHeight { get; set; }
    }
    public partial class PuddleText
    {
        [PrimaryKey]
        public Int64 IDPuddleText { get; set; }
        public Int64 IDDictionary { get; set; }
        [MaxLength(2147483647)]
        public String EntryText { get; set; }
    }
    public partial class SigninSignListSubTitles
    {
        [PrimaryKey]
        public Int64 IDSigninSignListSubTitle { get; set; }
        public Int64 IDSignListSubTitle { get; set; }
        public Int64 IDDictionary { get; set; }
        public Boolean isNewSign { get; set; }
        public Boolean isImportant { get; set; }
        public Int32 rank { get; set; }
        public Guid GUID { get; set; }
        public DateTime LastChange { get; set; }
    }
    public partial class SignList
    {
        [PrimaryKey]
        public Int64 IDSignList { get; set; }
        [MaxLength(2147483647)]
        public String SignListName { get; set; }
        public Guid GUID { get; set; }
        public DateTime LastChange { get; set; }
    }
    public partial class SignListSubTitles
    {
        [PrimaryKey]
        public Int64 IDSignListSubTitles { get; set; }
        public Int64 IDSignList { get; set; }
        [MaxLength(2147483647)]
        public String SubTitleName { get; set; }
        [MaxLength(2147483647)]
        public String MissingSigns { get; set; }
        public Int32 Rank { get; set; }
        public Guid GUID { get; set; }
        public DateTime LastChange { get; set; }
    }
    public partial class SignSequence
    {
        [PrimaryKey]
        public Int64 IDSignSequence { get; set; }
        public Int64 IDFrame { get; set; }
        public Int32 code { get; set; }
        public Int32 rank { get; set; }
    }
    public partial class SignSymbols
    {
        [PrimaryKey]
        public Int64 IDSignSymbols { get; set; }
        public Int64 IDFrame { get; set; }
        public Int32 code { get; set; }
        public Int32 x { get; set; }
        public Int32 y { get; set; }
        public Int32 z { get; set; }
        public Int32 hand { get; set; }
        public Int32 handcolor { get; set; }
        public Int32 palmcolor { get; set; }
        public Int32 size { get; set; }
    }
    public partial class Version
    {
        [PrimaryKey]
        public Int64 IDVersion { get; set; }
        public Int32 Major { get; set; }
        public Int32 Minor { get; set; }
        [MaxLength(2147483647)]
        public String DatabaseName { get; set; }
        [MaxLength(2147483647)]
        public String DatabaseType { get; set; }
    }
}
